### ISSUE TITLE
Build fails due to syntax error

### ISSUE THREAD

**Issue by joprice** [wravery/electron-cppgraphql#1]
I get the following error when trying to build using `npm install`:

`build/CMakeFiles/electron-cppgraphql.dir/flags.make:10: *** missing separator.  Stop.`

There seems to be a newline in the make file in CXX_INCLUDES between the nan dependency and the vcpkg dependencies. Removing the newline makes it build.

**Comment by wravery** [comment]
Interesting, I haven't tried regular makefile builds in a while. Is this on Unix/Linux or Windows?

**Comment by joprice** [comment]
I'm on a mac.
