### ISSUE TITLE
Support with cppgraphqlgen v3.5.0

### ISSUE THREAD

**Issue by arjangupta** [wravery/electron-cppgraphql#9]
Hi @wravery,

Thanks for creating this project! I tried compiling this project with cppgraphqlgen v3.5.0, but the compilation ran into multiple errors, most probably because this project expects cppgraphqlgen v3.0.0. Would it be possible to update this project for v3.5.0?

I'm happy to try to make changes for v.3.5.0 support, however, I haven't delved into the "Today" schema and how it's being used. Would I just need to correspondingly replace the contents of cppgraphqlgen/samples/ into the top level of this repository?

Thanks for your work on cppgraphqlgen as well.

**Comment by wravery** [comment]
Yup, this is something I've been meaning to do for a while. There's a much more recent sample in https://github.com/microsoft/electron-gqlmapi, although that's Windows-specific because of the https://github.com/microsoft/gqlmapi dependency.

**Comment by arjangupta** [comment]
I appreciate that, thanks.

As an additional question, if you don't mind - it seems that these electron examples are actually great representations of a GraphQL server instance. However, cppgraphqlgen should be easily usable in a client program as well, correct? I am trying to integrate cppgraphqlgen into a C++ client program that needs to send mutations and subscribe to a server.

**Comment by wravery** [comment]
I haven't really put much thought into C++ client scenarios. It may be possible to reuse parts of it, like the grammar to parse/validate queries. But as is, it's not particularly useful for a client, you can just pass strings back and forth for the GraphQL queries and the JSON results.

I opened https://github.com/microsoft/cppgraphqlgen/issues/161 to think about this some more. Meanwhile, if you just want to get started, there's another C++ client project mentioned on https://github.com/chentsulin/awesome-graphql, which is https://github.com/caffeinetv/CaffQL. I haven't tried it, but based on the README it seems like it's targeting your scenario.

**Comment by arjangupta** [comment]
That's really helpful, thank you!

**Comment by wravery** [comment]
I just updated this to work with v4.0.0.
